### PR TITLE
Migrate to flatlist

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by theneva** [comment]
Hi! I've sent a PR to the fork that should make the tests pass. It:

- Fixes the linting errors
- Downgrades React to ~15.5.4 (which is still an upgrade from 15.4.0-rc.4)
- Makes the `keyExtractor` prop optional, as it's also okay to pass a `key` to each `item` in `renderItem`

I'm pretty sure the examples need to be updated before this can land, though.

**Comment by kesha-antonov** [comment]
Hey! @theneva Merged

**Comment by Javier-Rotelli** [comment]
Great! i'm going to merge this. 
@theneva what was the problem you had that you had to downgrade react?

**Comment by theneva** [comment]
Awesome, thank you!

@Javier-Rotelli the issue is that react-native-mock imports proptypes directly off react, instead of from the prop-types package. That export disappeared from React in 15.6.

15.5 logs warnings during tests but doesn't break. 

react-native-mock is unmaintained and it wasn't super easy to get rid of it (I tried replacing mocha with jest to use its built-in mocking, but didn't try mockery which might be worth a look https://github.com/RealOrangeOne/react-native-mock/issues/139#issuecomment-415121472).

**Comment by theneva** [comment]
Oh btw @Javier-Rotelli it might be obvious but it hasn't been mentioned explicitly: the change to `renderItem` makes this a breaking change so it has to be released as a major. Is there anything preventing a release of this?

**Comment by Javier-Rotelli** [comment]
@theneva  not really, other than the time i needed to check if there were breaking changes or not.
i'll make the release and put up issues regarding prop-types and react-native-mock.

**Comment by theneva** [comment]
@Javier-Rotelli thank you very much! However, it seems like the actual publish to npm didn't go through (and it doesn't look like you're a collaborator on the package). If @mrlaessig gives you the right permissions, will you please try publishing it again? :smile:

**Comment by Javier-Rotelli** [comment]
yup, i need @mrlaessig 's permissions to publish

**Comment by mrlaessig** [comment]
Hey @Javier-Rotelli what it you npm username?

**Comment by Javier-Rotelli** [comment]
@mrlaessig  ->  `javierrotelli`

**Comment by mrlaessig** [comment]
@Javier-Rotelli You now should have the permission to do a release on npm ;)

**Pull request merged**
