### PR TITLE
adding ref for text input

### PR DESCRIPTION
**Pull request by mhendyl**
please approve this merge i need this ref prop for textinput

### CODE REVIEW

**Review by Lg0gs — APPROVED** [review]

**Review by Thanhal-P-A — APPROVED** [review]

**Comment by cavishek39** [comment]
@Lg0gs @Thanhal-P-A can you guys approve the PR, it's a very important feature?

**Comment by mrlaessig** [comment]
Try to implement it like this. There shouldn't be the need to introduce a new prop.

```
function SomeComponent() {
  const inputEl = useRef(null);
  return (
    <Autocomplete
      // ...
      renderTextInput={(props) => <TextInput {...props} ref={inputEl} />}
    />
  )
}
```

**Comment by cavishek39** [comment]
> <TextInput {...props} ref={inputEl} />

@mrlaessig thanks buddy, but still I feel this approach will be good if we use this package as a wrapper, but for someone who is directly using this package everywhere in their codebase, it'll not be ideal to refactor it everywhere.

**Comment by mrlaessig** [comment]
Resolved within #243. Now you can set the `ref` prop in the autocomplete to get a reference to the text input.

**Pull request closed without merging**
